fashionshop/Web/Models/ContactDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.Models
{
    public class ContactDetailViewModel
    {
        public int ID { set; get; }

        [Required(ErrorMessage = "Tên không được trống")]
        public string Name { set; get; }

        [MaxLength(50, ErrorMessage = "Số điện thoại không vượt quá 50 ký tự")]
        public string Phone { set; get; }

        [MaxLength(250, ErrorMessage = "Email không vượt quá 50 ký tự")]
        public string Email { set; get; }

        [MaxLength(250, ErrorMessage = "Website không vượt quá 50 ký tự")]
        public string Website { set; get; }

        [MaxLength(250, ErrorMessage = "Địa chỉ không vượt quá 50 ký tự")]
        public string Address { set; get; }

        public string Other { set; get; }

        public double? Lat { set; get; }

        public double? Lng { set; get; }

        public bool Status { set; get; }
    }
}

fashionshop/Web/Controllers/ContactDetailController.cs
using AutoMapper;
using BotDetect.Web.Mvc;
using Common;
using Model.Models;
using Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Infrastructure.Extensions;
using Web.Models;

namespace Web.Controllers
{
    public class ContactDetailController : Controller
    {
        IContactDetailService _contactDetailService;
        IFeedbackService _feedbackService;
        public ContactDetailController(IFeedbackService feedbackService,IContactDetailService contactDetailService)
        {
            this._contactDetailService = contactDetailService;
            this._feedbackService = feedbackService;
        }
        // GET: ContactDetail
        public ActionResult Index()
        {
            var newFeedbackViewModel = new FeedbackViewModel();
            newFeedbackViewModel.ContactDetail = GetContact();
            return View(newFeedbackViewModel);
        }

        private ContactDetailViewModel GetContact()
        {
            var contact = _contactDetailService.GetDefaultContact();
            var contactViewModel = Mapper.Map<ContactDetail, ContactDetailViewModel>(contact);
            return contactViewModel;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CaptchaValidation("CaptchaCode", "ExampleCaptcha", "Mã Captcha không đúng!")]
        public ActionResult SenFeedback(FeedbackViewModel feedbackVm)
        {
            if (ModelState.IsValid)
            {
                var newFeedback = new Feedback();
                newFeedback.UpdateFeedback(feedbackVm);
                _feedbackService.Create(newFeedback);
                _feedbackService.Save();

                ViewData["SuccessMsg"] = "Gửi phản hồi thành công.";

                var content = System.IO.File.ReadAllText(Server.MapPath("/Assets/client/templates/contact_template.html"));
                content = content.Replace("{{Name}}", feedbackVm.Name);
                content = content.Replace("{{Email}}", feedbackVm.Email);
                content = content.Replace("{{Phone}}", feedbackVm.Phone);
                content = content.Replace("{{Message}}", feedbackVm.Message);

                var adminEmail = ConfigHelper.GetByKey("AdminEmail");
                MailHelper.SendMail(adminEmail, "Thông tin liên hệ từ website Fashionshop", content);
            }
            
            feedbackVm.ContactDetail = GetContact();
            return View("Index",feedbackVm);
        }
    }
}

fashionshop/Web/Views/ContactDetail/Index.cshtml
@model Web.Models.FeedbackViewModel
@using BotDetect.Web.Mvc;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<link href="@BotDetect.Web.CaptchaUrls.Absolute.LayoutStyleSheetUrl" rel="stylesheet" type="text/css" />
<style>
    #map {
        width: 100%;
        height: 400px;
        background-color: grey;
    }
</style>
<div class="banner1">
    <div class="container">
        <h3><a href="/">Trang chủ</a> / <span>Liên hệ</span></h3>
    </div>
</div>

<input type="hidden" id="lat" value="@Model.ContactDetail.Lat" />
<input type="hidden" id="lng" value="@Model.ContactDetail.Lng" />
<div class="content">
    <!--contact-->
    <div class="mail-w3ls">
        <div class="container">
            <h2 class="tittle">Thông tin liên hệ</h2>
            <div class="mail-grids">
                <div class="mail-top">
                    <div class="col-md-4 mail-grid">
                        <i class="glyphicon glyphicon-map-marker" aria-hidden="true"></i>
                        <h5>Địa chỉ</h5>
                        <p>@Model.ContactDetail.Address</p>
                    </div>
                    <div class="col-md-4 mail-grid">
                        <i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>
                        <h5>Điện thoại</h5>
                        <p>Telephone:  @Model.ContactDetail.Phone</p>
                    </div>
                    <div class="col-md-4 mail-grid">
                        <i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>
                        <h5>E-mail</h5>
                        <p>E-mail:<a href="mailto:example@mail.com"> @Model.ContactDetail.Email</a></p>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="map-w3">
                    <div id="map"></div>
                </div>
                <div class="mail-bottom">
                    <h4>Liên lạc với chúng tôi</h4>
                    @using (Html.BeginForm("SenFeedback", "ContactDetail", FormMethod.Post))
                    {
                        if (ViewData["SuccessMsg"] != null)
                        {
                            <div class="alert alert-success" role="alert">
                                <strong>Chúc mừng bạn! </strong> gửi phản hồi thành công.
                                <br />Chúng tôi sẽ liên hệ lại sớm nhất có thể.
                            </div>
                        }
                        @Html.AntiForgeryToken();
                        @Html.ValidationSummary("", new { @class = "text-danger" })

                        @Html.TextBoxFor(x => x.Name, new { @placeholder = "Họ tên" })

                        @Html.TextBoxFor(x => x.Email, new { type = "email", @placeholder = "Email" })

                        @Html.TextBoxFor(x => x.Phone, new { @placeholder = "Điện thoại" })

                        @Html.TextAreaFor(x => x.Message, new { @rows = "5", @placeholder = "Tin nhắn của bạn" })

                        <div>
                            @{MvcCaptcha exampleCaptcha = new MvcCaptcha("ExampleCaptcha");
                            }
                            @Html.Captcha(exampleCaptcha)<br />
                            @Html.TextBox("CaptchaCode")
                            <div class="clearfix"></div>
                        </div><br />
                        <input type="submit" value="Gửi">
                        <input type="reset" value="Nhập lại">
                    }
                </div>
            </div>
        </div>
    </div>
    <!--contact-->
</div>

<script src="~/Assets/client/js/controllers/contact.js"></script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAzxucoCn8j_10N3QC5EMoj8GXw-UIRAgk&callback=initMap">
</script>
